### ISSUE TITLE
Fixed number of decimal places

### ISSUE THREAD

**Issue by rmpt** [roman910dev/currency_formatter#11]
Hi,
I'm trying to format a value with 2 decimal places, that works when it's different from 0, but I want to always see the decimal places, even if it's 0.
For instance, to format `3` I want to see `3.00`.
I've tried setting `decimal` to 2, played around with `compact` but nothing worked as needed.

Also, it would be nice to be able to format with no currency at all, in cases like a table, where you have the currency on the header and you don't want to repeat the currency symbol on all rows. In that case it would be nice to just round the value to the defined decimal places.

Thanks

**Comment by roman910dev** [comment]
For the case where you want to enforce the number of decimal places displayed, you can set `enforceDecimals` to `true`, which is disabled by default. Here's an example of how you would do it:

```dart
const amount = 3;
String enforceDecimal = CurrencyFormatter.format(
    amount,
    euroSettings,
    enforceDecimals: true,
  ); // 3,00 €
```

To display a formatted value without the currency symbol, you can set `symbol` and `symbolSeparator` to empty strings.

```dart
const amount = 1910.9347;
final noSymbolFormat = euroSettings.copyWith(symbol: '', symbolSeparator: '');
String noSymbol =
    CurrencyFormatter.format(amount, noSymbolFormat); // 1.910,93
```

I will add these examples to the example and test files.
