### ISSUE TITLE
How do I convert the converted format to double ?

### ISSUE THREAD

**Issue by Patrick386** [roman910dev/currency_formatter#5]
How do I convert the converted format to double ?
Example: 2,500.25 € -> 2500.25

**Comment by mayken** [comment]
@Patrick386 
String source = "2,500.25 €".replaceAll(RegExp(r"\D"), "");
double result = (int.tryParse(source) ?? 0) / 100;

**Comment by roman910dev** [comment]
I've just uploaded a new version (1.2.1) to pub.dev that supports parsing formatted strings to numbers using CurrencyFormatter().parse(). I hope it is what you wanted.
