### ISSUE TITLE
individual space character

### ISSUE THREAD

**Issue by Surio89** [roman910dev/currency_formatter#7]
The space character between the number and the currency symbol should be customizable.

i would like to use "thin space" character https://www.compart.com/en/unicode/U+2009

**Comment by roman910dev** [comment]
I've added this option in the latest version (2.0.0).

You can now set the `symbolSeparator` parameter of a `CurrencyFormatterSettings`.

Or you could also do:

```dart
CurrencyFormatterSettings usdThinSpace = CurrencyFormatterSettings.usd.copyWith(symbolSeparator: '\u2009');
```

I hope that's what you wanted.

Also, keep in mind that this version brings major changes and some code will have to be migrated.
